In [195]:
from sklearn.tree import DecisionTreeClassifier

In [196]:
import pandas as pd
import numpy as np
import os
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [197]:
current_directory = os.getcwd()

credit_file = os.path.join(current_directory, 'credit.csv')

base_credit = pd.read_csv(credit_file)
base_credit2 = base_credit.drop(base_credit[base_credit['person_age'] < 0].index)

X_credit = base_credit2.iloc[:, [0,1,6]].values

y_credit = base_credit2.iloc[:, 8].values

scaler_base = StandardScaler()
X_credit = scaler_base.fit_transform(X_credit)

In [198]:
X_credit_training, X_credit_test, y_credit_training, y_credit_test = train_test_split(X_credit, y_credit, test_size=0.2, random_state=0)

In [199]:
X_credit_test.shape

(6517, 3)

In [200]:
X_credit_training

array([[-0.58831303, -0.58201979, -0.72593778],
       [-0.58831303, -0.19481165, -1.32701437],
       [-0.11572182, -0.59815346,  0.06495248],
       ...,
       [-0.90337383, -0.44488358, -0.09322557],
       [-0.74584343, -0.38841572,  0.06495248],
       [-0.74584343, -0.5174851 ,  0.21522163]])

In [201]:
y_credit_training

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [202]:
arvore_credit = DecisionTreeClassifier(criterion='entropy')
arvore_credit.fit(X_credit_training, y_credit_training)

DecisionTreeClassifier(criterion='entropy')

In [203]:
arvore_credit.feature_importances_

array([0.22289577, 0.46990857, 0.30719566])

In [204]:
prevision = arvore_credit.predict(X_credit_test)

In [205]:
prevision

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [206]:
y_credit_test

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [207]:
accuracy_score(prevision, y_credit_test)

0.8123369648611324