In [156]:
from sklearn.tree import DecisionTreeClassifier

In [157]:
import pandas as pd
import numpy as np
import os
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [158]:
current_directory = os.getcwd()

credit_file = os.path.join(current_directory, 'credit.csv')

base_credit = pd.read_csv(credit_file)
base_credit2 = base_credit.drop(base_credit[base_credit['person_age'] < 0].index)

X_credit = base_credit2.iloc[:, [0,1,6,9,11]].values

y_credit = base_credit2.iloc[:, 8].values

scaler_base = StandardScaler()
X_credit = scaler_base.fit_transform(X_credit)

In [159]:
X_credit_training, X_credit_test, y_credit_training, y_credit_test = train_test_split(X_credit, y_credit, test_size=0.2, random_state=43)

In [160]:
X_credit_training

array([[-0.58831303, -0.19481165,  1.64673299,  1.87110215, -0.69155444],
       [-0.43078263, -0.53361877, -0.39376387,  0.46634625, -0.44494161],
       [-0.27325222,  0.67640667,  0.53948663, -0.47015768, -0.69155444],
       ...,
       [ 0.82946059,  0.07946078,  1.09310981,  0.55999664,  0.04828407],
       [ 0.04180858, -0.48521776, -1.21233529, -1.12571044,  0.54150975],
       [-0.58831303,  0.54733729,  0.53948663, -0.37650729, -0.44494161]])

In [161]:
y_credit_training

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [162]:
arvore_credit = DecisionTreeClassifier(criterion='entropy')
arvore_credit.fit(X_credit, y_credit)

DecisionTreeClassifier(criterion='entropy')

In [163]:
arvore_credit.feature_importances_

array([0.16282336, 0.3186053 , 0.15015019, 0.2556268 , 0.11279436])

In [164]:
prevision = arvore_credit.predict(X_credit_test)

In [165]:
prevision

array([0, 1, 0, ..., 0, 1, 0], dtype=int64)

In [166]:
y_credit_test

array([0, 1, 0, ..., 0, 1, 0], dtype=int64)

In [167]:
accuracy_score(prevision, y_credit_test)

0.9904864201319625