In [209]:
from sklearn.tree import DecisionTreeClassifier

In [210]:
import pandas as pd
import numpy as np
import os
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [211]:
current_directory = os.getcwd()

credit_file = os.path.join(current_directory, 'credit.csv')

base_credit = pd.read_csv(credit_file)
base_credit2 = base_credit.drop(base_credit[base_credit['person_age'] < 0].index)

X_credit = base_credit2.iloc[:, [0,1,6]].values

y_credit = base_credit2.iloc[:, 8].values

scaler_base = StandardScaler()
X_credit = scaler_base.fit_transform(X_credit)

In [212]:
base_credit

person_age  person_income person_home_ownership  person_emp_length  \
0              22          59000                  RENT              123.0   
1              21           9600                   OWN                5.0   
2              25           9600              MORTGAGE                1.0   
3              23          65500                  RENT                4.0   
4              24          54400                  RENT                8.0   
...           ...            ...                   ...                ...   
32576          57          53000              MORTGAGE                1.0   
32577          54         120000              MORTGAGE                4.0   
32578          65          76000                  RENT                3.0   
32579          56         150000              MORTGAGE                5.0   
32580          66          42000                  RENT                2.0   

           loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
0             PERSONAL          D      35000          16.02            1   
1            EDUCATION          B       1000          11.14            0   
2              MEDICAL          C       5500          12.87            1   
3              MEDICAL          C      35000          15.23            1   
4              MEDICAL          C      35000          14.27            1   
...                ...        ...        ...            ...          ...   
32576         PERSONAL          C       5800          13.16            0   
32577         PERSONAL          A      17625           7.49            0   
32578  HOMEIMPROVEMENT          B      35000          10.99            1   
32579         PERSONAL          B      15000          11.48            0   
32580          MEDICAL          B       6475           9.99            0   

       loan_percent_income cb_person_default_on_file  \
0                     0.59                         Y   
1                     0.10                         N   
2                     0.57                         N   
3                     0.53                         N   
4                     0.55                         Y   
...                    ...                       ...   
32576                 0.11                         N   
32577                 0.15                         N   
32578                 0.46                         N   
32579                 0.10                         N   
32580                 0.15                         N   

       cb_person_cred_hist_length  
0                               3  
1                               2  
2                               3  
3                               2  
4                               4  
...                           ...  
32576                          30  
32577                          19  
32578                          28  
32579                          26  
32580                          30  

[32581 rows x 12 columns]

In [213]:
X_credit_training, X_credit_test, y_credit_training, y_credit_test = train_test_split(X_credit, y_credit, test_size=0.2, random_state=0)

In [214]:
X_credit_test.shape

(6517, 3)

In [215]:
X_credit_training

array([[-0.58831303, -0.58201979, -0.72593778],
       [-0.58831303, -0.19481165, -1.32701437],
       [-0.11572182, -0.59815346,  0.06495248],
       ...,
       [-0.90337383, -0.44488358, -0.09322557],
       [-0.74584343, -0.38841572,  0.06495248],
       [-0.74584343, -0.5174851 ,  0.21522163]])

In [216]:
y_credit_training

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [217]:
arvore_credit = DecisionTreeClassifier(criterion='entropy')
arvore_credit.fit(X_credit_training, y_credit_training)

DecisionTreeClassifier(criterion='entropy')

In [218]:
arvore_credit.feature_importances_

array([0.22393946, 0.47153147, 0.30452907])

In [219]:
prevision = arvore_credit.predict(X_credit_test)

In [220]:
prevision

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [221]:
y_credit_test

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [222]:
accuracy_score(prevision, y_credit_test)

0.8141783029001074